### ISSUE TITLE
Error installing from manager

### ISSUE THREAD

**Issue by aitormendez** [ChrisColeTech/ComfyUI-Elegant-Resource-Monitor#4]
ComfyUI-Elegant-Resource-Monitor install failed: Bad Request

**Comment by ChrisColeTech** [comment]
I'm not able to reproduce this in a new comfyui installation. 

If anyone else runs into this issue, please retry the installation -  

- delete the resource monitor custom_node folder, 
- click 'update all' in ComfyUI Manager, 
- and reinstall the plugin
- close ComfyUi and relaunch

**Comment by aitormendez** [comment]
Ok, thank you.
